package cronjob_test

import (
	"context"
	"fmt"

	"github.com/ludusrusso/nats-kit/cronjob"
	"github.com/ludusrusso/nats-kit/natstest"
)

// Example declares one Cron Job in the "billing" namespace and waits for its
// first two Ticks.
//
// Nothing here schedules anything in-process: Register validates the Schedule
// expression, Run stores it on the broker, and every Tick after that is
// generated by the NATS server. Running this same code in three replicas
// would still fire the job once per Tick.
func Example() {
	// An Example has no *testing.T, so it uses StartServer rather than
	// Start. In a real test, natstest.Start(t) is the one you want.
	nc, cleanup, err := natstest.StartServer()
	if err != nil {
		fmt.Println(err)
		return
	}
	defer cleanup()

	ctx, cancel := context.WithCancel(context.Background())

	// quiet() discards the Runner's own logs so they stay out of this
	// example's output; a real service passes its own slog.Logger, or
	// nothing at all and gets slog.Default().
	runner, err := cronjob.New(ctx, nc, "billing", quiet())
	if err != nil {
		panic(err)
	}

	ticks := make(chan cronjob.Tick, 2)
	sweep := cronjob.NewJob("sweep_expired", "@every 1s", func(_ context.Context, tick cronjob.Tick) error {
		// A real handler would do the sweeping here. Returning an error
		// would be logged and the Tick acked anyway: a failed run is not
		// retried, it simply happens again at the next Tick.
		ticks <- tick
		return nil
	})

	if err := runner.Register(sweep); err != nil {
		panic(err)
	}

	runErr := make(chan error, 1)
	go func() { runErr <- runner.Run(ctx) }()

	// A one-second Schedule keeps the example fast; a real job is measured
	// in minutes or hours. There is no immediate run at startup — the first
	// Tick lands one full interval after Run stores the Schedule.
	first, second := <-ticks, <-ticks

	cancel()
	<-runErr

	fmt.Println("sweep_expired fired twice:", !first.ScheduledAt.IsZero() && second.ScheduledAt.After(first.ScheduledAt))
	fmt.Println("each Tick knows when the next one falls due:", !first.NextAt.IsZero())

	// Output:
	// sweep_expired fired twice: true
	// each Tick knows when the next one falls due: true
}
